#Configuration
VERBOSE: False
MODEL:
  MODE: 'DeFlare'
# Optimization arguments.
TRAINOPTIM:
  BATCH: 16 # origin: 2
  EPOCHS: 300
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-4 #origin: 2e-4
  LR_MIN: 1e-6 # origin: 1e-6
  # BETA1: 0.9
TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256 # origin: 256
  VAL_PS: 512
  FLARE_DIR: './dataset/Flare7Kpp/Flare7K'       # path to training data
  GT_DIR: './dataset/Flickr24K'       # path to training data
  VAL_DIR: './dataset/Flare7Kpp/Flare7K/test_date/real'
  SAVE_DIR: './checkpoints'           # path to save models and images
TESTING:
  TEST_PS: None
  TEST_DIR: './dataset/Flare7Kpp/Flare7K/test_data/real' # path to validation data
  TEST_DIR_SYN: './dataset/Flare7Kpp/Flare7K/test_data/real' # path to validation data
  WEIGHT_ROOT: './checkpoints/models'
  WEIGHT_NAME: '/model_bestLPIPS.pth'